### PR TITLE
[rac_brahui] Brahui keyboard in latin script

### PR DESCRIPTION
**Pull request by rachitralli**
Brahui keyboard in Latin script by Rehmat Aziz Chitrali

### CODE REVIEW

**Comment by rachitralli** [comment]
This branch has no conflicts with the base branch, can anybody check this? thanks

**Comment by rachitralli** [comment]
@DavidLRowe sir please check this

**Comment by DavidLRowe** [comment]
@rachitralli Although the title indicates this keyboard uses Latin script, it seems to be an Arabic script keyboard. You have already submitted a rac_brahui keyboard which has been published (https://keyman.com/keyboards/rac_brahui).

**Comment by rachitralli** [comment]
@DavidLRowe sir the rac_brahui keyboard in arabic script has already been created but the users of Brahui language are using both the latin and arabic scripts keyboard, therefore I have created this PR for latin script. If you have some spare time please look at this and approve, please thanks

**Comment by DavidLRowe** [comment]
@rachitralli As far as I can see, the keyboard is producing Arabic script characters. Please check the files again.

**Comment by rachitralli** [comment]
@DavidLRowe sir let me check again, thanks

**Comment by rachitralli** [comment]
@DavidLRowe corrected Readme.md, rac_brahui.keyboard_info, rac_brahui.php, and welcome.htm please check now, thanks

**Comment by rachitralli** [comment]
@DavidLRowe please create PR for this keyboard on my behalf

**Comment by DavidLRowe** [comment]
I'm confused. I think previously you had files named `rac_brahui_latin` that actually produced Arabic script characters. Now the files seem to be named `rac_brahui` but producing Latin script characters. The `rac_brahui` keyboard name is already used for the Arabic script keyboard, so it cannot be used again. Could you please check your files again? Thanks

**Comment by rachitralli** [comment]
@DavidLRowe let me check please

**Comment by rachitralli** [comment]
@DavidLRowe please wait I have started to re-draft the keyboard as desired. thanks

**Comment by rachitralli** [comment]
@DavidLRowe please check you  email, I have emailed to the updated files for this keyboard. thanks

**Comment by rachitralli** [comment]
This keyboard has been approved, please see https://github.com/keymanapp/keyboards/pull/926#issuecomment-549012527 therefore I am closing this PR as done.

**Pull request closed without merging**
