### PR TITLE
[rac_pashai] Initial Pashai Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Pashai Language Keyboard by Rehmat Aziz Chitrali

### CODE REVIEW

**Comment by rachitralli** [comment]
@DavidLRowe @LornaSIL this branch showing no conflicts with the base branch, pls check

**Comment by rachitralli** [comment]
@LornaSIl if you have some spare time please check this keyboard, regards

**Comment by LornaSIL** [comment]
This keyboard is already online: https://keyman.com/keyboards/rac_pashto

**Comment by LornaSIL** [comment]
Oh, sorry. That was Pashto.

**Comment by LornaSIL** [comment]
Okay, this keyboard is on your repo, not the Keyman repo. But anyway, I will submit a PR with the fixed up files. However, can you test the keyboard? I had to make some changes because some characters were on the desktop layout, but they were not on the mobile layout. Other characters were on the mobile layout, but they were not on the desktop layout. I tried to make them consistent. Let me know if it looks okay.
Here's the link to download the .kmp: https://drive.google.com/open?id=13e0l1QoFsA737ah6D4_RZQYp1aM7NSq2

**Comment by rachitralli** [comment]
Checked in Desktop, but in my language bar its shows Pashto (Afghanistan) instead Pashai (Afghanistan) please check in your computer, please check this
rac pashai

**Comment by rachitralli** [comment]
@LornaSIL checked in Desktop, but in my language bar its shows Pashto (Afghanistan) instead Pashai (Afghanistan) please check in your computer, please check this

**Comment by DavidLRowe** [comment]
@rachitralli What version of Windows are you using? 

I installed rac_pashai and it shows as "Southeast Pashayi (psi-Arab-AF)". I also installed rac_pashto.

image

**Comment by rachitralli** [comment]
@DavidLRowe windows  10 sir

**Comment by rachitralli** [comment]
@DavidLRowe this is now ok

**Comment by rachitralli** [comment]
@DavidLRowe @LornaSIL

**Comment by LornaSIL** [comment]
This keyboard is already available online here: https://keyman.com/keyboards/rac_pashai
You can close this Pull Request.

**Comment by rachitralli** [comment]
This keyboard is available online here: https://keyman.com/keyboards/rac_pashai
therefore i am closing this Pull Request.

**Pull request closed without merging**
