### PR TITLE
[rac_oadki] Initial Oadki Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Oadki Language Keyboard by Rehmat Aziz Chitrali

### CODE REVIEW

**Comment by rachitralli** [comment]
@MakaraSOK if you have time please check this, thanks

**Comment by rachitralli** [comment]
@LornaSIL if you have spare time please check this, thanks

**Comment by LornaSIL** [comment]
Yes, I'll work on this. I have a higher priority this week, but I should get to it soon.

**Comment by rachitralli** [comment]
@LornaSIL thanks

**Comment by rachitralli** [comment]
@LornaSIL

**Comment by LornaSIL** [comment]
This keyboard is now available here: https://keyman.com/keyboards/rac_oadki
You can delete this Pull Request.

**Comment by rachitralli** [comment]
@LornaSIL thank you very much for approving this pakistani language i.e. Oadki language keyboard.  This keyboard is now available here: https://keyman.com/keyboards/rac_oadki
therefore I am deleting this Pull Request as Done.

**Pull request closed without merging**
