### PR TITLE
Bug in keyman 10.0

### PR DESCRIPTION
**Pull request by rachitralli**
I am using keyman 10.0 while compiling an arabic script keyboard the keyman 10.0 crashed many times and now the arabic letters has automatically been converted into roman letter, please help and fix the issue. thanks here is the screen shot
image

### CODE REVIEW

**Comment by rachitralli** [comment]
@LornaSIL I have a Khowar-Urdu-Dictionary and want to upload this dictionary into https://rachitrali.webonary.org this dictionary in word doc format, please share the latest version of toolbox software

**Comment by LornaSIL** [comment]
> 
> 
> @LornaSIL I have a Khowar-Urdu-Dictionary and want to upload this dictionary into https://rachitrali.webonary.org this dictionary in word doc format, please share the latest version of toolbox software

I'm not sure what kind of help you are looking for. Is this related to keyboards? If it's related to webonary.org you may want to ask them for assistance. https://www.webonary.org/help/

Toolbox link: https://software.sil.org/toolbox/ (this application is not currently being developed, but you can still use it)

FieldWorks Language Explorer link: https://software.sil.org/fieldworks/

**Comment by rachitralli** [comment]
the issue has been resolved, please close this pr

**Comment by rachitralli** [comment]
The issue of Windows 10 has been resolved. therefore I am closing this PR as done.

**Pull request closed without merging**
