### PR TITLE
[rac_arabic] Arabic Phonetic Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Arabic Language Phonetic Keyboard by Rehmat Aziz Chitrali

### CODE REVIEW

**Comment by rachitralli** [comment]
@darcywong00 if you have time please check this thanks --~~~~

**Comment by darcywong00** [comment]
Hi there
@MakaraSok should be able to help you with this.

Some important things to fix:
1. Save off your rac_pahar, rac_pashto, and rac_arabic files (you'll be updating your master branch, and don't want to lose that work)

2. You'll need to get your master branch in sync with the main repo.
See: https://help.keyman.com/developer/keyboards/advanced/step-2.php

3. Currently, you've added "rac_pahari" and "rac_pashto" on the master branch of your keyboards fork.
Those need to be moved to separate `rac_pahari` and `rac_pashto` branches.
    a. rac_pahari should be in a folder `release/rac/rac_pahari` on a branch called `rac_pahari`
    b. rac_pashto should be in a folder `release/rac/rac_pashto` on a branch called `rac_pahari`
    c. rac_arabic should be in a folder `release/rac/rac_arabic` on a branch called `rac_arabic`.

Then you can create the PR on the keymanapp/keyboards repo

**Comment by rachitralli** [comment]
@MakaraSok welcome back, please check this as and when you have time, thanks

**Comment by rachitralli** [comment]
hi @MakaraSok if you have time pls see this

**Comment by rachitralli** [comment]
@MakaraSok darcywong00 please check this

**Comment by darcywong00** [comment]
The pull request needs to be created in the main keyboards repo

https://github.com/keymanapp/keyboards/compare/master...rachitralli:keymanappmasterrachitralli-rac_arabic

**Before** you make the pull request, there's a lot of extra files on your `keymanappmasterrachitralli-rac_arabic` branch that will need to be removed because they're not related to the rac_arabic keyboard.

@MakaraSok or @LornaSIL would be the people to assist you.

**Comment by rachitralli** [comment]
@MakaraSok  @LornaSIL please check this thanks

**Comment by LornaSIL** [comment]
I submitted this keyboard on your behalf: https://github.com/keymanapp/keyboards/pull/900
You can close this Pull Request.

(Your cloned repo is so old compared to the current repo: https://github.com/keymanapp/keyboards that you might be better off deleting your repo and recloning before you attempt to do any other keyboards. Also, you should use the newest version of Keyman Developer. It might help you to get all your files in the right place.)

**Comment by rachitralli** [comment]
@LornaSIl how can i clone my repo? please guide me thanks

**Comment by LornaSIL** [comment]
You should delete your repo and re-clone the keymanapp repo.
Here are the instructions for working with Keyman Developer and the Github repo. It would be good for you to review them again before trying to submit more keyboards:
https://help.keyman.com/developer/keyboards/advanced/

**Comment by rachitralli** [comment]
this keyboard is now ready for use. please click here https://keyman.com/keyboards/rac_arabic

**Pull request closed without merging**
