### PR TITLE
[rac_parkari_koli] Initial Parkari-Koli Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Initial Parkari-Koli Language Keyboard by Rehmat Aziz Chitrali

### CODE REVIEW

**Comment by rachitralli** [comment]
@DavidLRowe sir I have uploaded the Pakrari-Koli keyboard files into my master branch instead of rachitralii/keyboards pls shift these into the relevant folder. regards

**Comment by rachitralli** [comment]
@DavidLRowe sir if you have spare time please check this, thanks

**Comment by rachitralli** [comment]
@DavidLRowe sir if you have spare time please check this, thanks

**Comment by DavidLRowe** [comment]
The files in this pull request were submitted to the keymanapp/keyboards repository as pull request 634 (https://github.com/keymanapp/keyboards/pull/634), which has been merged into master. You should be able to access this keyboard from the keyman.com site.

**Comment by rachitralli** [comment]
this keyboard is available at https://keyman.com/keyboards/rac_parkari_koli
therefore I am closing this pull request

**Comment by rachitralli** [comment]
this keyboard is available at https://keyman.com/keyboards/rac_parkari_koli
therefore I am closing this pull request

**Pull request closed without merging**
