### PR TITLE
Initial Marwari Keyboard

### PR DESCRIPTION
**Pull request by rachitralli**
Marwari Keyboard in Pakistani language by Rehmat Aziz Chitrali

### CODE REVIEW

**Comment by rachitralli** [comment]
@MakaraSok If you have spare time please look at this PR

**Comment by rachitralli** [comment]
@MakaraSok If you have spare time please look at this PR

**Comment by rachitralli** [comment]
@LornaSIL if you have some spare time please see this, thanks

**Comment by LornaSIL** [comment]
I will look at it when I get a chance, which may be a few weeks. In the meantime, please verify that the files all follow the structure as you've learned for the other keyboards.

**Comment by rachitralli** [comment]
@LornaSIL after approving this keyboard please update my master branch by deleting and merging my files in the relevant folder.

**Comment by LornaSIL** [comment]
I've submitted the marwari keyboard on the Keyman website. I do not have permissions to do anything on your branch. Unfortunately, you will have to do the work on deleting your clone and recreating it.

**Comment by rachitralli** [comment]
this Marwari language keyboard has been approved at https://github.com/keymanapp/keyboards/pull/942
therefore i am closing this PR as done

**Pull request closed without merging**
